#!/bin/bash

# Get the name of the local and remote branches
local_branch=$(git symbolic-ref HEAD | sed 's!refs\/heads\/!!')
remote_branch=$(git rev-parse --abbrev-ref @{u})

# Check if the local branch has been rebased onto the remote branch
if ! git merge-base --is-ancestor $remote_branch $local_branch; then
    echo "Your changes have not been rebased onto $remote_branch. Please use 'git pull --rebase' instead of 'git pull' to update your local repository."
    exit 1
fi
